# Generated by Django 3.0.3 on 2020-07-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_changed_my_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('BLUE', 'blue'), ('GREEN', 'green'), ('ORANGE', 'orange'), ('gray', 'gray'), ('BLACK', 'black')], default=('BLUE', 'blue'), max_length=12),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('APPS', 'apps'), ('LAN', 'lan'), ('ADJUST', 'adjust'), ('ADOBE', 'adobe'), ('AIR_HORN', 'air-horn')], default=('APPS', 'apps'), max_length=12),
        ),
    ]
