# Generated by Django 3.0.3 on 2020-07-19 12:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_changed_my_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to=products.models.upload_post_image),
        ),
    ]
